name = "builder_firewood"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0035d164-091d-4f5a-af16-68deb8d2c5d0"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "0035d164-091d-4f5a-af16-68deb8d2c5d0"

[[permissions]]
permission = "area_control.command.mark"
value = true

[permissions.context]
"area_control:current_area_id" = "0035d164-091d-4f5a-af16-68deb8d2c5d0"
