name = "builder_youpolazi"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0028b4ae-7d18-4b39-9428-a97d38922482"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "0028b4ae-7d18-4b39-9428-a97d38922482"

[[permissions]]
permission = "area_control.command.mark"
value = true

[permissions.context]
"area_control:current_area_id" = "0028b4ae-7d18-4b39-9428-a97d38922482"
