name = "builder_firesource"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0003de32-6d7f-4889-ac37-6f5e06f81503"

[[permissions]]
permission = "weight.10"
value = true
