name = "builder_civilization_fire"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "003ef6e3-1b17-4b9b-b705-80c3af861144"

[[permissions]]
permission = "weight.10"
value = true
