name = "builder_lostgrace"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0049a190-2ecd-47ef-897d-7183467d31b8"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "0049a190-2ecd-47ef-897d-7183467d31b8"
