name = "builder_apiary"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0050b806-5f11-4ff2-a2ed-76bfc1316473"

[[permissions]]
permission = "weight.10"
value = true
