name = "builder_f_a_r"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "003cb99d-0225-453b-bc11-8347c09b9cb6"

[[permissions]]
permission = "weight.10"
value = true
