name = "builder_umapyoi"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0043c2e8-5681-482d-9de0-cc21e185e289"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "0043c2e8-5681-482d-9de0-cc21e185e289"

[[permissions]]
permission = "area_control.command.mark"
value = true

[permissions.context]
"area_control:current_area_id" = "0043c2e8-5681-482d-9de0-cc21e185e289"
