name = "builder_gravity_generator"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0032f5ee-14f6-4fc3-bc4c-6b1fead3ec55"

[[permissions]]
permission = "weight.10"
value = true
