name = "builder_item_and_block_properties"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0019d6a9-73ee-4c08-bd10-476388eeabf7"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "0019d6a9-73ee-4c08-bd10-476388eeabf7"

[[permissions]]
permission = "area_control.command.mark"
value = true

[permissions.context]
"area_control:current_area_id" = "0019d6a9-73ee-4c08-bd10-476388eeabf7"
