name = "builder_boomood"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "000fe7e1-4204-47df-8cb7-c6dd275329ed"

[[permissions]]
permission = "weight.10"
value = true
