name = "builder_exp1182"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "001ee409-b3fd-4b15-97a5-393dc8af75c7"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "001ee409-b3fd-4b15-97a5-393dc8af75c7"
