name = "builder_caupona"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0034f23c-03cf-4186-9bfb-37af920d3391"

[[permissions]]
permission = "weight.10"
value = true
