name = "builder_meteorcertainidea"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0025e473-ffd4-49a6-94ac-6988bbdce6b7"
