name = "builder_handle_cane"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "003daedc-54a8-47cf-b7d2-9e2ab96cfb6c"
