name = "builder_spaceplane"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0018e4d9-d70f-461d-b380-b3958f64ec0c"
