name = "builder_pyrotechnicraft"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0048f940-14e4-48ea-a661-3714c8aea77e"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "0048f940-14e4-48ea-a661-3714c8aea77e"
