name = "builder_ntr"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0022bc1d-0c89-4827-8605-9ddc023b03f8"

[[permissions]]
permission = "weight.10"
value = true
