name = "builder_metallurgy"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "002bcca5-7d0f-4d3a-aaf7-dbc2b84ba8a4"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "002bcca5-7d0f-4d3a-aaf7-dbc2b84ba8a4"

[[permissions]]
permission = "area_control.command.mark"
value = true

[permissions.context]
"area_control:current_area_id" = "002bcca5-7d0f-4d3a-aaf7-dbc2b84ba8a4"
