name = "builder_beacons"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0029a7de-3be1-4f89-bca2-a444b3aade0e"

[[permissions]]
permission = "weight.10"
value = true
