name = "builder_artoftnt"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0036dffb-69b9-48f7-8516-200ba5dd57c9"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "0036dffb-69b9-48f7-8516-200ba5dd57c9"

[[permissions]]
permission = "area_control.command.mark"
value = true

[permissions.context]
"area_control:current_area_id" = "0036dffb-69b9-48f7-8516-200ba5dd57c9"
