name = "builder_groundfire"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "claim-000dffca-1dcc-4b71-b096-73cde7918f26"
