name = "builder_simplebbq"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "002ee38d-b813-4bf0-b067-b1be995ca73d"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "002ee38d-b813-4bf0-b067-b1be995ca73d"
