name = "builder_briquettes"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0012a287-ee94-4035-aff5-5c26b0817515"

[[permissions]]
permission = "weight.10"
value = true
