name = "mod"

[[permissions]]
permission = "worldedit.*"
value = true

[[permissions]]
permission = "area_control.*"
value = true

[[permissions]]
permission = "*"
value = true

[[parents]]
group = "builder"
