name: TeaCon 2022 create tag

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Release Candidate Version
        id: rc
        run: |
          tags=`git tag --points-at HEAD`
          if [[ -z $tags ]]; then
            current_rc=(`git tag | while read tag; do
              [[ $tag =~ v(3\.[0-9.]+)-rc\.([0-9]+) ]] && echo ${BASH_REMATCH[1]} ${BASH_REMATCH[2]}
            done | sort -n -k1 | tail -n1`)
            echo "The next tag to be created will be v${current_rc[0]}-rc.$((${current_rc[1]}+1))."
            echo "::set-output name=next::v${current_rc[0]}-rc.$((${current_rc[1]}+1))"
            echo "::set-output name=exists::true"
          else
            echo "::warning::The current commit has already been marked as $tags, skipping tag creation."
          fi
      - name: Create Tag
      - uses: rickstaa/action-create-tag@v1
        if: steps.rc.outputs.exists == 'true'
        with:
          tag: ${{ steps.rc.outputs.next }}
