name: TeaCon 2022 deploy to build server

on:
  push:
    tags: [ 'v3.*' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Auth as Github App
        id: auth-as-github-app
        uses: tibdex/github-app-token@v1
        if: github.event_name == 'workflow_dispatch'
        with:
          app_id: ${{ secrets.TEACON_BOT_ID }}
          private_key: ${{ secrets.TEACON_BOT_PRIVATE_KEY }}
          installation_id: ${{ secrets.TEACON_BOT_INSTALLATION_ID }}
      - name: Generate Release Candidate Version
        id: generate-next-rc
        if: github.event_name == 'workflow_dispatch'
        run: |
          tags=`git tag --points-at HEAD`
          if [[ -z $tags ]]; then
            current_rc=(`git tag | while read tag; do
              [[ $tag =~ v(3\.[0-9.]+)-rc\.([0-9]+) ]] && echo ${BASH_REMATCH[1]} ${BASH_REMATCH[2]}
            done | sort -n -k2 | tail -n1`)
            echo "The next tag to be created will be v${current_rc[0]}-rc.$((${current_rc[1]}+1))."
            echo "::set-output name=next::v${current_rc[0]}-rc.$((${current_rc[1]}+1))"
            echo "::set-output name=exists::true"
          else
            echo "::warning::The current commit has already been marked as $tags, skipping tag creation."
          fi
      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        if: github.event_name == 'workflow_dispatch' && steps.generate-next-rc.outputs.exists == 'true'
        with:
          tag: ${{ steps.generate-next-rc.outputs.next }}
          github_token: ${{ steps.auth-as-github-app.outputs.token }}
      - name: Check Differences
        id: diff
        env:
          HEAD: ${{ github.sha }}
        run: |
          # calculate BASE
          BASE=`git describe --tags --abbrev=0 "$HEAD"^ 2>/dev/null || echo`

          # calculate diff count
          git_flags=`[[ -z $BASE ]] && echo ls-files || echo diff --name-only $HEAD $BASE`
          mods_diff=`git $git_flags -- 2022/mod-list-build.json | wc -l`
          assets_diff=`git $git_flags -- 2022/assets 2022/pack.mcmeta | wc -l`
          data_diff=`git $git_flags -- 2022/data 2022/pack.mcmeta | wc -l`
          serverconfig_diff=`git $git_flags -- 2022/serverconfig | wc -l`
          config_diff=`git $git_flags -- 2022/config | wc -l`

          # set diff count output
          echo "::set-output name=mods::$mods_diff"
          echo "::set-output name=assets::$assets_diff"
          echo "::set-output name=data::$data_diff"
          echo "::set-output name=serverconfig::$serverconfig_diff"
          echo "::set-output name=config::$config_diff"
      - name: Handle Mods
        if: steps.diff.outputs.mods > 0
        env:
          RUN: ${{ github.run_number }}
        run: |
          # rename mod list json
          cp 2022/mod-list-build.json mod-list-build-$RUN.json
      - name: Handle Assets
        if: steps.diff.outputs.assets > 0
        env:
          RUN: ${{ github.run_number }}
        run: |
          # zip assets
          cd 2022; zip -r9Xo ../assets-build-$RUN.zip assets pack.mcmeta
      - name: Handle Data
        if: steps.diff.outputs.data > 0
        env:
          RUN: ${{ github.run_number }}
        run: |
          # zip data
          cd 2022; zip -r9Xo ../data-build-$RUN.zip data pack.mcmeta
      - name: Handle Config
        if: steps.diff.outputs.config > 0
        env:
          RUN: ${{ github.run_number }}
        run: |
          # zip config
          cd 2022; zip -r9Xo ../config-build-$RUN.zip config
      - name: Handle Server Config
        if: steps.diff.outputs.serverconfig > 0
        env:
          RUN: ${{ github.run_number }}
        run: |
          # zip server config
          cd 2022; zip -r9Xo ../serverconfig-build-$RUN.zip serverconfig
      - name: Deploy to Longjing Server
        env:
          HEAD: ${{ github.sha }}
          RUN: ${{ github.run_number }}
          SSH_PRIVATE_KEY: ${{ secrets.TEACON_LONGJING_SSH_PRIVATE_KEY }}
        run: |
          # deploy ssh private key
          cat > ~/id_ecdsa <<< $SSH_PRIVATE_KEY
          chmod 0600 ~/id_ecdsa # good permissions
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          ssh-keyscan -H 2022.teacon.cn >> ~/.ssh/known_hosts

          # copy to longjing server
          dest=longjing@2022.teacon.cn:deploy/
          echo Considering git ref $HEAD with build number $RUN
          [[ -f mod-list-build-$RUN.json ]] && scp -i ~/id_ecdsa mod-list-build-$RUN.json $dest
          [[ -f assets-build-$RUN.zip ]] && scp -i ~/id_ecdsa assets-build-$RUN.zip $dest
          [[ -f data-build-$RUN.zip ]] && scp -i ~/id_ecdsa data-build-$RUN.zip $dest
          [[ -f config-build-$RUN.zip ]] && scp -i ~/id_ecdsa config-build-$RUN.zip $dest
          [[ -f serverconfig-build-$RUN.zip ]] && scp -i ~/id_ecdsa serverconfig-build-$RUN.zip $dest

          # run deploy command
          ssh -i ~/id_ecdsa longjing@2022.teacon.cn flock deploy.lock bash deploy-build.sh $RUN
          echo Finished deploying to the build server.
