name: TeaCon 2022 build test modpack

on:
  push:
    branches: [ dev ]
    paths:
      - "2022/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Get Short Identifier
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Build Test Modpack
        env:
          COMMIT_SHA: ${{ steps.short-sha.outputs.sha }}
        run: |
          bash .github/build_modpack.sh -f 40.1.25 -m 1.18.2 -p "TeaCon 2022" \
             -v 3.0.0-SNAPSHOT -d 2022/servers-test.dat -r 2022/remote-sync-test.json 2022/
          cp TeaCon2022-3.0.0-SNAPSHOT.zip TeaCon2022-3.0.0-SNAPSHOT-$COMMIT_SHA.zip
      - name: Build Shaded Modpack
        env:
          COMMIT_SHA: ${{ steps.short-sha.outputs.sha }}
        run: |
          bash .github/build_modpack.sh -s -f 40.1.25 -m 1.18.2 -p "TeaCon 2022" \
             -v 3.0.0-SNAPSHOT-Shaded -d 2022/servers-test.dat -r 2022/remote-sync-test.json 2022/
          cp TeaCon2022-3.0.0-SNAPSHOT-Shaded.zip TeaCon2022-3.0.0-SNAPSHOT-$COMMIT_SHA-Shaded.zip
      - name: Upload to TeaCon Archive
        env:
          S3_ENDPOINT: ${{ secrets.TEACON_ARCHIVE_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.TEACON_ARCHIVE_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEACON_ARCHIVE_SECRET_KEY }}
        run: |
          for zip in `ls TeaCon2022-*.zip | tac`; do
            echo Uploading "$zip" to "s3://2022/modpack/$zip" ...
            aws s3 cp --endpoint-url $S3_ENDPOINT `realpath $zip` "s3://2022/modpack/$zip"
          done
